"""
Analytical Gravitational Acceleration of a Homogeneous Rectangular Cuboid
=======================================================================

This module provides an exact analytical formulation for the gravitational
acceleration (gravity vector) generated by a homogeneous rectangular cuboid,
evaluated at arbitrary field points in three-dimensional space.

The implementation follows closed-form expressions derived from Newtonian
gravitational theory using a vertex-based formulation. All acceleration
components are evaluated analytically; no numerical differentiation or
numerical approximation is employed.

Input
-----
Field points are specified by Cartesian coordinates (x, y, z).
The cuboid is defined by half-dimensions L, B, and D, volume mass density
rho_vol, and gravitational constant G.

Output
------
The gravitational acceleration vector components (gx, gy, gz) are returned,
corresponding to the negative spatial gradient of the gravitational potential
evaluated at the specified field points.

Batch evaluation
----------------
For efficient evaluation at a large number of field points, the function
``gravitational_acceleration_batch`` accepts an array of points with shape
(N, 3) and returns arrays of acceleration components (gx, gy, gz). For
sufficiently large N, the computation is automatically parallelized across
available CPU cores.

Author
------
Thunendran Periyandy
Division of Geodetic Science
The Ohio State University

"""



# CuboidGravitationalField/acceleration.py
import numpy as np
from CuboidGravitationalField.safe_math import sp_log, sp_arctan
from multiprocessing import Pool, cpu_count

"""
Gravitational acceleration of a homogeneous cuboid using the
vertex-based closed-form formulation.

This implementation strictly follows the mathematical development:

  • Oriented face–distance coordinates        (Sec. 2.1)
  • Regularized logarithmic and arctangent    (Sec. 2.2)
  • Acceleration kernel 𝓚(X,Y,Z)              (Eq. (kernel))
  • Component permutations                    (Eq. (g_general))
  • Vertex sign symmetry S = (-1)^{i_x+i_y+i_z}

The kernel is fully analytic at interior / boundary / exterior points,
with all singularities canceled by vertex antisymmetry.

The script provides:
    g_core(...)                   – kernel evaluation
    gravitational_gx_cuboid(...) – x-component of acceleration
    gravitational_gy_cuboid(...) – y-component of acceleration
    gravitational_gz_cuboid(...) – z-component of acceleration

Plus optional:
    gravitational_acceleration_point(...)
    gravitational_acceleration_batch(...)

The code is vectorized over the 8 vertices and may execute in parallel
for many evaluation points (N > 100).
"""

# ================================================================
# Precomputed vertex signs  S = (-1)^{i_x+i_y+i_z}
# ================================================================
_VERTEX_SIGNS = np.array(
    [(-1.0) ** (i_x + i_y + i_z)
     for i_x in (0, 1)
     for i_y in (0, 1)
     for i_z in (0, 1)],
    dtype=float
)


# ================================================================
# Oriented vertex coordinates (signed face distances)
# ================================================================
def _vertex_coordinates(x, y, z, L, B, D):
    """
    Generates the 8 oriented vertex distances:

        X = ±(L ± x)
        Y = ±(B ± y)
        Z = ±(D ± z)

    The signs are arranged so that the alternating vertex sign
    S = (-1)^{i_x+i_y+i_z} appears explicitly in the sum, matching
    the analytical formulation.

    Returns
    -------
    X, Y, Z : ndarray shape (8,)
    S       : ndarray shape (8,)
        Vertex coordinate triples and signs.
    """
    X_bounds = np.array([L - x, -(L + x)], dtype=float)
    Y_bounds = np.array([B - y, -(B + y)], dtype=float)
    Z_bounds = np.array([D - z, -(D + z)], dtype=float)

    X = np.repeat(X_bounds, 4)
    Y = np.tile(np.repeat(Y_bounds, 2), 2)
    Z = np.tile(Z_bounds, 4)

    return X, Y, Z, _VERTEX_SIGNS


# ================================================================
# Core acceleration kernel  𝓚(X,Y,Z)  (Eq. (kernel))
# ================================================================
def g_core(x_j, x_k, x_l, X_comp, Y_comp, Z_comp):
    """
    Core kernel evaluated per vertex, using scalar sp_log and sp_arctan.
    All inputs are length-8 arrays (vertices).
    """
    out = np.zeros_like(x_j, dtype=float)

    for i in range(8):
        Xc = X_comp[i]
        Yc = Y_comp[i]
        Zc = Z_comp[i]

        r = np.sqrt(Xc*Xc + Yc*Yc + Zc*Zc)

        # Evaluate scalar special_log and special_arctan
        term1 = x_j[i] * sp_log(x_k[i] + r)
        term2 = x_k[i] * sp_log(x_j[i] + r)

        num = x_j[i] * x_k[i]
        den = x_l[i] * r

        term3 = - x_l[i] * sp_arctan(num, den)

        out[i] = term1 + term2 + term3

    return out


# ================================================================
# Gravitational acceleration components
# ================================================================

def gravitational_gx_cuboid(x, y, z, L, B, D, rho_vol, G):
    """
    g_x component of gravitational acceleration.

    Implements:

        g_x = -G ρ  Σ_vertex  S ⋅ 𝓚(Y, Z, X),

    following the (U_x, V_x, W_x) = (X, Y, Z) mapping of the theory.

    Returns
    -------
    gx : float
    """
    X, Y, Z, S = _vertex_coordinates(x, y, z, L, B, D)

    # Kernel arguments:
    #   x_l = X  (axis)
    #   x_j = Y
    #   x_k = Z
    kernel = g_core(x_j=Y, x_k=Z, x_l=X,
                    X_comp=X, Y_comp=Y, Z_comp=Z)

    return -G * rho_vol * np.sum(S * kernel)


def gravitational_gy_cuboid(x, y, z, L, B, D, rho_vol, G):
    """
    g_y component of gravitational acceleration.

    Implements:

        g_y = -G ρ Σ S ⋅ 𝓚(X, Z, Y),

    corresponding to (U_y, V_y, W_y) = (Y, X, Z).

    Returns
    -------
    gy : float
    """
    X, Y, Z, S = _vertex_coordinates(x, y, z, L, B, D)

    kernel = g_core(x_j=X, x_k=Z, x_l=Y,
                    X_comp=X, Y_comp=Y, Z_comp=Z)

    return -G * rho_vol * np.sum(S * kernel)


def gravitational_gz_cuboid(x, y, z, L, B, D, rho_vol, G):
    """
    g_z component of gravitational acceleration.

    Implements:

        g_z = -G ρ Σ S ⋅ 𝓚(X, Y, Z),

    corresponding to (U_z, V_z, W_z) = (Z, X, Y).

    Returns
    -------
    gz : float
    """
    X, Y, Z, S = _vertex_coordinates(x, y, z, L, B, D)

    kernel = g_core(x_j=X, x_k=Y, x_l=Z,
                    X_comp=X, Y_comp=Y, Z_comp=Z)

    return -G * rho_vol * np.sum(S * kernel)


# ================================================================
# Convenience wrapper: acceleration vector at a point
# ================================================================
def gravitational_acceleration_point(x, y, z, L, B, D, rho_vol, G):
    gx = gravitational_gx_cuboid(x, y, z, L, B, D, rho_vol, G)
    gy = gravitational_gy_cuboid(x, y, z, L, B, D, rho_vol, G)
    gz = gravitational_gz_cuboid(x, y, z, L, B, D, rho_vol, G)
    return gx, gy, gz


# ================================================================
# Parallel & batch evaluation
# ================================================================
def _single_point_accel(args):
    x, y, z, L, B, D, rho_vol, G = args
    return gravitational_acceleration_point(x, y, z, L, B, D, rho_vol, G)


def gravitational_acceleration_batch(points, L, B, D, rho_vol, G,
                                     parallel_threshold=100):
    """
    Evaluate acceleration for many points.
    Automatically uses multiprocessing if N > parallel_threshold.

    Parameters
    ----------
    points : array_like shape (N,3)
    L,B,D : floats     – half-dimensions of the cuboid
    rho_vol : float    – density
    G       : float    – gravitational constant
    parallel_threshold : int  – enable parallelization if N > threshold

    Returns
    -------
    gx, gy, gz : ndarray shape (N,)
    """
    pts = np.asarray(points, dtype=float)
    N = pts.shape[0]

    args_list = [(p[0], p[1], p[2], L, B, D, rho_vol, G) for p in pts]

    # Use parallel execution only for large workloads
    if N > parallel_threshold:
        with Pool(cpu_count()) as pool:
            results = pool.map(_single_point_accel, args_list)
    else:
        results = list(map(_single_point_accel, args_list))

    gx, gy, gz = map(np.array, zip(*results))
    return gx, gy, gz
