"""
Analytical Gravitational Tensor of a Homogeneous Rectangular Cuboid
===================================================================

This module provides an exact analytical formulation for the gravitational
tensor (gravity-gradient tensor) generated by a homogeneous rectangular
cuboid, evaluated at arbitrary field points in three-dimensional space.

The implementation follows closed-form expressions derived from Newtonian
gravitational theory using a vertex-based formulation. The tensor components
correspond to the second spatial derivatives of the analytical gravitational
potential and are evaluated analytically; no numerical differentiation or
numerical approximation is employed.

Input
-----
Field points are specified by Cartesian coordinates (x, y, z).
The cuboid is defined by half-dimensions L, B, and D, volume mass density
rho, and gravitational constant G.

Output
------
The gravitational tensor is returned as a 3×3 matrix T whose components are
(Vxx, Vyy, Vzz, Vxy, Vxz, Vyz), corresponding to the second spatial
derivatives of the gravitational potential evaluated at the specified field
points. For a single point, the output has shape (3, 3).

Batch evaluation
----------------
For efficient evaluation at a large number of field points, the function
``gravitational_tensor_batch`` accepts an array of points with shape (N, 3)
and returns an array of tensors with shape (N, 3, 3). For sufficiently large
N, the computation is automatically parallelized across available CPU cores.

Author
------
Thunendran Periyandy
Division of Geodetic Science
The Ohio State University

"""
# CuboidGravitationalField/tensor.py
import numpy as np
from CuboidGravitationalField.safe_math import sp_log, sp_arctan
from multiprocessing import Pool, cpu_count

# =========================================================
# VERTEX COORDINATES & SIGNS
# =========================================================

# Precomputed vertex signs S = (-1)^{i_x+i_y+i_z}
_VERTEX_SIGNS = np.array(
    [(-1.0) ** (ix + iy + iz)
     for ix in (0, 1)
     for iy in (0, 1)
     for iz in (0, 1)],
    dtype=float
)


def _vertex_coordinates(x, y, z, L, B, D):
    """
    Build the 8 oriented vertex coordinates (X, Y, Z) and their signs S.

    Xb = [ L - x,  -(L + x) ]
    Yb = [ B - y,  -(B + y) ]
    Zb = [ D - z,  -(D + z) ]

    X,Y,Z arrays are length-8, ordered consistently with _VERTEX_SIGNS.
    """
    Xb = np.array([L - x, -(L + x)], dtype=float)
    Yb = np.array([B - y, -(B + y)], dtype=float)
    Zb = np.array([D - z, -(D + z)], dtype=float)

    X = np.repeat(Xb, 4)
    Y = np.tile(np.repeat(Yb, 2), 2)
    Z = np.tile(Zb, 4)

    return X, Y, Z, _VERTEX_SIGNS


# =========================================================
# CORE TENSOR FUNCTIONS (ARRAY INPUT, SCALAR SAFE MATH)
# =========================================================

def tensor_core_ln(x_rem, r_val):
    """
    Vectorized version of ln(x_rem + r) using scalar sp_log.

    Parameters
    ----------
    x_rem : ndarray
        Remaining axis coordinate (e.g., Z, Y, or X).
    r_val : ndarray
        Radial distances R = sqrt(X^2 + Y^2 + Z^2).

    Returns
    -------
    ln_vals : ndarray
        special_log(x_rem + R) evaluated at each vertex.
    """
    x_rem = np.asarray(x_rem, dtype=float)
    r_val = np.asarray(r_val, dtype=float)

    out = np.zeros_like(x_rem, dtype=float)
    for i in range(len(out)):
        out[i] = sp_log(x_rem[i] + r_val[i])
    return out


def tensor_core_atan(x_i, x_j, x_k, r_val):
    """
    Vectorized version of arctan( x_j * x_k / (x_i * r) ) using scalar sp_arctan.

    Parameters
    ----------
    x_i : ndarray
        Axis associated with the second derivative (e.g., X for V_xx).
    x_j, x_k : ndarray
        The other two coordinates.
    r_val : ndarray
        Radial distances R = sqrt(X^2 + Y^2 + Z^2).

    Returns
    -------
    atan_vals : ndarray
        special_arctan(x_j x_k, x_i R) for each vertex.
    """
    x_i = np.asarray(x_i, dtype=float)
    x_j = np.asarray(x_j, dtype=float)
    x_k = np.asarray(x_k, dtype=float)
    r_val = np.asarray(r_val, dtype=float)

    out = np.zeros_like(x_i, dtype=float)
    for i in range(len(out)):
        num = x_j[i] * x_k[i]
        den = x_i[i] * r_val[i]
        out[i] = sp_arctan(num, den)
    return out


# =========================================================
# DIAGONAL COMPONENTS (V_xx, V_yy, V_zz)
# =========================================================

def gravitational_Vxx_cuboid(x, y, z, L, B, D, rho, G):
    """
    V_xx = ∂²V/∂x²

    Implements:

        V_xx = -G ρ ∑_vertices S · special_arctan( YZ, X R )
    """
    X, Y, Z, S = _vertex_coordinates(x, y, z, L, B, D)
    R = np.sqrt(X*X + Y*Y + Z*Z)

    atan_vals = tensor_core_atan(X, Y, Z, R)
    S_sum = np.sum(S * atan_vals)
    return -G * rho * S_sum


def gravitational_Vyy_cuboid(x, y, z, L, B, D, rho, G):
    """
    V_yy = ∂²V/∂y²

    Implements:

        V_yy = -G ρ ∑ S · special_arctan( XZ, Y R )
    """
    X, Y, Z, S = _vertex_coordinates(x, y, z, L, B, D)
    R = np.sqrt(X*X + Y*Y + Z*Z)

    atan_vals = tensor_core_atan(Y, X, Z, R)
    S_sum = np.sum(S * atan_vals)
    return -G * rho * S_sum


def gravitational_Vzz_cuboid(x, y, z, L, B, D, rho, G):
    """
    V_zz = ∂²V/∂z²

    Implements:

        V_zz = -G ρ ∑ S · special_arctan( XY, Z R )
    """
    X, Y, Z, S = _vertex_coordinates(x, y, z, L, B, D)
    R = np.sqrt(X*X + Y*Y + Z*Z)

    atan_vals = tensor_core_atan(Z, X, Y, R)
    S_sum = np.sum(S * atan_vals)
    return -G * rho * S_sum


# =========================================================
# OFF-DIAGONAL COMPONENTS (V_xy, V_xz, V_yz)
# =========================================================
# These use: - ln( x_rem + R )

def gravitational_Vxy_cuboid(x, y, z, L, B, D, rho, G):
    """
    V_xy = V_yx = ∂²V/(∂x∂y)

    Implements:

        V_xy = -G ρ ∑ S · [ - special_log(Z + R) ]
             =  G ρ ∑ S · special_log(Z + R)
    """
    X, Y, Z, S = _vertex_coordinates(x, y, z, L, B, D)
    R = np.sqrt(X*X + Y*Y + Z*Z)

    ln_vals = tensor_core_ln(Z, R)
    S_sum = np.sum(S * (-ln_vals))
    return -G * rho * S_sum


def gravitational_Vxz_cuboid(x, y, z, L, B, D, rho, G):
    """
    V_xz = V_zx = ∂²V/(∂x∂z)

    Implements:

        V_xz = -G ρ ∑ S · [ - special_log(Y + R) ]
             =  G ρ ∑ S · special_log(Y + R)
    """
    X, Y, Z, S = _vertex_coordinates(x, y, z, L, B, D)
    R = np.sqrt(X*X + Y*Y + Z*Z)

    ln_vals = tensor_core_ln(Y, R)
    S_sum = np.sum(S * (-ln_vals))
    return -G * rho * S_sum


def gravitational_Vyz_cuboid(x, y, z, L, B, D, rho, G):
    """
    V_yz = V_zy = ∂²V/(∂y∂z)

    Implements:

        V_yz = -G ρ ∑ S · [ - special_log(X + R) ]
             =  G ρ ∑ S · special_log(X + R)
    """
    X, Y, Z, S = _vertex_coordinates(x, y, z, L, B, D)
    R = np.sqrt(X*X + Y*Y + Z*Z)

    ln_vals = tensor_core_ln(X, R)
    S_sum = np.sum(S * (-ln_vals))
    return -G * rho * S_sum


# =========================================================
# FULL TENSOR AT A POINT
# =========================================================

def gravitational_tensor_cuboid(x, y, z, L, B, D, rho, G):
    """
    Return the full 3x3 gravitational tensor:

        T = [[V_xx, V_xy, V_xz],
             [V_xy, V_yy, V_yz],
             [V_xz, V_yz, V_zz]]
    """
    V_xx = gravitational_Vxx_cuboid(x, y, z, L, B, D, rho, G)
    V_yy = gravitational_Vyy_cuboid(x, y, z, L, B, D, rho, G)
    V_zz = gravitational_Vzz_cuboid(x, y, z, L, B, D, rho, G)

    V_xy = gravitational_Vxy_cuboid(x, y, z, L, B, D, rho, G)
    V_xz = gravitational_Vxz_cuboid(x, y, z, L, B, D, rho, G)
    V_yz = gravitational_Vyz_cuboid(x, y, z, L, B, D, rho, G)

    return np.array(
        [[V_xx, V_xy, V_xz],
         [V_xy, V_yy, V_yz],
         [V_xz, V_yz, V_zz]],
        dtype=float
    )


# =========================================================
# BATCH + PARALLEL EVALUATION
# =========================================================

def _single_point_tensor(args):
    x, y, z, L, B, D, rho, G = args
    return gravitational_tensor_cuboid(x, y, z, L, B, D, rho, G)


def gravitational_tensor_batch(points, L, B, D, rho, G,
                               parallel_threshold=100):
    """
    Evaluate the gravitational tensor at many points.

    Parameters
    ----------
    points : array_like, shape (N, 3)
        Evaluation points [ [x0,y0,z0], [x1,y1,z1], ... ].
    L, B, D : float
        Half-dimensions of the cuboid.
    rho : float
        Volume mass density.
    G : float
        Gravitational constant.
    parallel_threshold : int, optional
        Use multiprocessing if N > parallel_threshold (default: 100).

    Returns
    -------
    T : ndarray shape (N, 3, 3)
        Tensor at each point.
    """
    pts = np.asarray(points, dtype=float)
    if pts.ndim != 2 or pts.shape[1] != 3:
        raise ValueError("points must be an array of shape (N, 3)")

    N = pts.shape[0]
    args_list = [(p[0], p[1], p[2], L, B, D, rho, G) for p in pts]

    if N > parallel_threshold:
        with Pool(cpu_count()) as pool:
            tensors = pool.map(_single_point_tensor, args_list)
    else:
        tensors = [_single_point_tensor(a) for a in args_list]

    return np.stack(tensors, axis=0)
