# Triangle_GP.py
"""
Analytical Gravitational Field of a Uniform Triangle
============================================================

This module provides exact analytical formulations for the gravitational
potential, gravitational acceleration (gravity vector), and gravitational
tensor (gravity-gradient tensor) generated by a homogeneous planar triangle,
evaluated at arbitrary field points in three-dimensional space.

The implementation follows closed-form expressions derived from Newtonian
gravitational theory and is suitable for use as a fundamental surface-mass
primitive in polygonal and polyhedral gravity modeling.

Input
-----
The triangle is defined by three vertices given in Cartesian
coordinates as an array of shape (3, 3): [v0, v1, v2]. Physical parameters
include the gravitational constant G and surface mass density sigma.
Field points are specified by Cartesian coordinates (x, y, z), provided as:
  • a single point with shape (3,), or
  • an array of points with shape (N, 3).

Output
------
• Potential: ``potential(points)`` returns U as a scalar (single point) or
  an array of shape (N,).
• Acceleration: ``acceleration(points)`` returns the gravity vector g as an
  array of shape (3,) (single point) or (N, 3).
• Tensor: ``gravity_tensor(points)`` returns the gravity-gradient tensor Γ
  (Jacobian of acceleration) as an array of shape (3, 3) (single point) or
  (N, 3, 3).

Batch and parallel evaluation
-----------------------------
For efficient evaluation at a large number of field points, the class
provides parallel batch methods that accept an array of points with shape
(N, 3) and return outputs with the shapes described above:
  • ``potential_parallel(points, n_workers=None, chunk_size=...)``
  • ``acceleration_parallel(points, n_workers=None, chunk_size=...)``
  • ``gravity_tensor_parallel(points, n_workers=None, chunk_size=...)``

Author
------
Thunendran Periyandy
Division of Geodetic Science
The Ohio State University

"""

import os
import numpy as np
from concurrent.futures import ProcessPoolExecutor


def sp_log_vec(x: np.ndarray) -> np.ndarray:
    """Vectorized safe log: log(x) for x>0 else 0."""
    x = np.asarray(x, dtype=np.float64)
    out = np.zeros_like(x, dtype=np.float64)
    ok = x > 0.0
    out[ok] = np.log(x[ok])
    bad = ~np.isfinite(out)
    if np.any(bad):
        out[bad] = 0.0
    return out


def sp_atan2_like_vec(y: np.ndarray, x: np.ndarray, eps: float = 0.0) -> np.ndarray:
    """
    atan2(y, x) WITHOUT np.atan2, WITH correct quadrant handling.
    Returns angle in (-pi, pi].
    """
    y = np.asarray(y, dtype=np.float64)
    x = np.asarray(x, dtype=np.float64)
    yb, xb = np.broadcast_arrays(y, x)
    out = np.zeros_like(yb, dtype=np.float64)

    x_ok = np.abs(xb) > eps
    with np.errstate(divide="ignore", invalid="ignore"):
        base = np.arctan(yb / xb)

    corr = np.zeros_like(out)
    negx = x_ok & (xb < 0.0)
    corr[negx & (yb >= 0.0)] = np.pi
    corr[negx & (yb < 0.0)] = -np.pi

    out[x_ok] = base[x_ok] + corr[x_ok]

    x_bad = ~x_ok
    y_pos = x_bad & (yb > eps)
    y_neg = x_bad & (yb < -eps)
    out[y_pos] = 0.5 * np.pi
    out[y_neg] = -0.5 * np.pi

    bad = ~np.isfinite(out)
    if np.any(bad):
        out[bad] = 0.0
    return out


def _chunk_points(P: np.ndarray, chunk_size: int):
    n = P.shape[0]
    if chunk_size is None or chunk_size <= 0:
        yield (0, n, P)
        return
    for i in range(0, n, chunk_size):
        j = min(i + chunk_size, n)
        yield (i, j, P[i:j])


# --------------------------------------------------------------------
# Parallel worker globals
# --------------------------------------------------------------------
_TRI_WORKER_OBJ = None


def _tri_worker_init(state: dict):
    global _TRI_WORKER_OBJ
    _TRI_WORKER_OBJ = TriangleLaminaGravitation(
        state["vertices"], G=state["G"], sigma=state["sigma"], eps=state["eps"]
    )


def _tri_worker_potential(Pchunk: np.ndarray) -> np.ndarray:
    return _TRI_WORKER_OBJ.potential(Pchunk)


def _tri_worker_acceleration(Pchunk: np.ndarray) -> np.ndarray:
    return _TRI_WORKER_OBJ.acceleration(Pchunk)


def _tri_worker_tensor(Pchunk: np.ndarray) -> np.ndarray:
    return _TRI_WORKER_OBJ.gravity_tensor(Pchunk)


class TriangleLaminaGravitation:
    """
    Uniform triangular lamina (surface density sigma).

    Potential:
        V = G*sigma*( Σ p_e * log_e  - z*Omega )

    Acceleration:
        g = G*sigma*( Σ log_e*u_hat_e  - Omega*n_hat )

    Tensor:
        Γ = G*sigma*( Σ u_hat_e ⊗ ∇log_e  - n_hat ⊗ ∇Omega )

    This version returns Γ WITHOUT symmetrization (no np.swapaxes).
    """

    def __init__(self, vertices: np.ndarray, G: float = 1.0, sigma: float = 1.0, eps: float = 0.0):
        v = np.asarray(vertices, dtype=np.float64)
        if v.shape != (3, 3):
            raise ValueError("vertices must be shape (3,3): [v0,v1,v2].")

        self.G = float(G)
        self.sigma = float(sigma)
        self.eps = float(eps)

        self.v0 = np.ascontiguousarray(v[0])
        self.v1 = np.ascontiguousarray(v[1])
        self.v2 = np.ascontiguousarray(v[2])

        n_raw = np.cross(self.v1 - self.v0, self.v2 - self.v0)
        n_norm = np.linalg.norm(n_raw)
        if not np.isfinite(n_norm) or n_norm <= self.eps:
            raise ValueError("Degenerate triangle (area ~ 0) or invalid normal.")
        self.n_hat = n_raw / n_norm

        # Directed edges: (0->1), (1->2), (2->0)
        self.ea = np.ascontiguousarray(np.stack([self.v0, self.v1, self.v2], axis=0))  # (3,3)
        self.eb = np.ascontiguousarray(np.stack([self.v1, self.v2, self.v0], axis=0))  # (3,3)

        evec = self.eb - self.ea
        self.L = np.linalg.norm(evec, axis=1)
        if np.any(~np.isfinite(self.L)) or np.any(self.L <= self.eps):
            raise ValueError("Degenerate edge length encountered.")

        self.t_hat = evec / self.L[:, None]
        self.u_hat = np.cross(self.t_hat, self.n_hat[None, :])

        # cached broadcast-friendly view (no change in math)
        self._L_row = self.L[None, :]  # (1,3)

    # -----------------------------
    # shared per-call precomputations (no sign/definition changes)
    # -----------------------------
    def _edge_vectors_and_lengths(self, P: np.ndarray):
        """
        Compute endpoint vectors and distances for all 3 edges.
        Returns:
          ra_vec, rb_vec: (B,3,3)
          ra, rb:         (B,3)
        """
        ra_vec = self.ea[None, :, :] - P[:, None, :]
        rb_vec = self.eb[None, :, :] - P[:, None, :]
        ra = np.linalg.norm(ra_vec, axis=2)
        rb = np.linalg.norm(rb_vec, axis=2)
        return ra_vec, rb_vec, ra, rb

    @staticmethod
    def _log_term(ra: np.ndarray, rb: np.ndarray, L_edge: np.ndarray, eps: float) -> np.ndarray:
        # EXACTLY your original logic
        ra = np.asarray(ra, dtype=np.float64)
        rb = np.asarray(rb, dtype=np.float64)
        L = np.asarray(L_edge, dtype=np.float64)
        if L.ndim == 1:
            L = L[None, :]

        s = ra + rb
        den = s - L
        ok = (L > eps) & (den > eps)

        with np.errstate(divide="ignore", invalid="ignore"):
            ratio = (s + L) / den

        ok2 = ok & (ratio > 0.0)
        out = np.where(ok2, sp_log_vec(ratio), 0.0)

        bad = ~np.isfinite(out)
        if np.any(bad):
            out[bad] = 0.0
        return out

    @staticmethod
    def _solid_angle_and_grad(P: np.ndarray, v0: np.ndarray, v1: np.ndarray, v2: np.ndarray, eps: float):
        P = np.atleast_2d(np.asarray(P, dtype=np.float64))

        r0 = v0[None, :] - P
        r1 = v1[None, :] - P
        r2 = v2[None, :] - P

        r0n = np.linalg.norm(r0, axis=1)
        r1n = np.linalg.norm(r1, axis=1)
        r2n = np.linalg.norm(r2, axis=1)

        c12 = np.cross(r1, r2)
        c20 = np.cross(r2, r0)
        c01 = np.cross(r0, r1)

        T = np.einsum("ij,ij->i", c12, r0, optimize=True)

        d01 = np.einsum("ij,ij->i", r0, r1, optimize=True)
        d12 = np.einsum("ij,ij->i", r1, r2, optimize=True)
        d20 = np.einsum("ij,ij->i", r2, r0, optimize=True)

        D = (r0n * r1n * r2n + d01 * r2n + d12 * r0n + d20 * r1n)

        Omega = 2.0 * sp_atan2_like_vec(T, D, eps=eps)

        gradT = -(c12 + c20 + c01)

        inv_r0 = np.zeros_like(r0n)
        inv_r1 = np.zeros_like(r1n)
        inv_r2 = np.zeros_like(r2n)

        ok0 = r0n > eps
        ok1 = r1n > eps
        ok2 = r2n > eps
        inv_r0[ok0] = 1.0 / r0n[ok0]
        inv_r1[ok1] = 1.0 / r1n[ok1]
        inv_r2[ok2] = 1.0 / r2n[ok2]

        grad_r0n = -r0 * inv_r0[:, None]
        grad_r1n = -r1 * inv_r1[:, None]
        grad_r2n = -r2 * inv_r2[:, None]

        grad_d01 = -(r0 + r1)
        grad_d12 = -(r1 + r2)
        grad_d20 = -(r2 + r0)

        gradD1 = (
            grad_r0n * (r1n * r2n)[:, None]
            + grad_r1n * (r0n * r2n)[:, None]
            + grad_r2n * (r0n * r1n)[:, None]
        )
        gradD2 = grad_d01 * r2n[:, None] + grad_r2n * d01[:, None]
        gradD3 = grad_d12 * r0n[:, None] + grad_r0n * d12[:, None]
        gradD4 = grad_d20 * r1n[:, None] + grad_r1n * d20[:, None]
        gradD = gradD1 + gradD2 + gradD3 + gradD4

        denom = (T * T + D * D)
        gradOmega = np.zeros_like(gradT)

        ok = denom > eps
        with np.errstate(divide="ignore", invalid="ignore"):
            gradOmega[ok] = 2.0 * ((D[ok, None] * gradT[ok] - T[ok, None] * gradD[ok]) / denom[ok, None])

        bad = ~np.isfinite(Omega)
        if np.any(bad):
            Omega[bad] = 0.0
        bad = ~np.isfinite(gradOmega)
        if np.any(bad):
            gradOmega[bad] = 0.0

        return Omega, gradOmega

    # -----------------------------
    # API (
    # -----------------------------
    def potential(self, points: np.ndarray) -> np.ndarray:
        P_in = np.asarray(points)
        P = np.atleast_2d(np.asarray(points, dtype=np.float64))
        eps = self.eps

        z = np.einsum("ij,j->i", self.v0[None, :] - P, self.n_hat, optimize=True)
        Omega, _ = self._solid_angle_and_grad(P, self.v0, self.v1, self.v2, eps)

        ra_vec, rb_vec, ra, rb = self._edge_vectors_and_lengths(P)

        p = np.einsum("bkj,kj->bk", ra_vec, self.u_hat, optimize=True)
        logE = self._log_term(ra, rb, self.L, eps)

        edge_sum = np.sum(p * logE, axis=1)
        V = self.G * self.sigma * (edge_sum - z * Omega)

        return V[0] if P_in.ndim == 1 else V

    def acceleration(self, points: np.ndarray) -> np.ndarray:
        P_in = np.asarray(points)
        P = np.atleast_2d(np.asarray(points, dtype=np.float64))
        eps = self.eps

        Omega, _ = self._solid_angle_and_grad(P, self.v0, self.v1, self.v2, eps)

        ra_vec, rb_vec, ra, rb = self._edge_vectors_and_lengths(P)

        logE = self._log_term(ra, rb, self.L, eps)

        edge_vec = np.einsum("bk,kj->bj", logE, self.u_hat, optimize=True)
        face_vec = -Omega[:, None] * self.n_hat[None, :]

        g = self.G * self.sigma * (edge_vec + face_vec)
        return g[0] if P_in.ndim == 1 else g

    def gravity_tensor(self, points: np.ndarray) -> np.ndarray:
        """
        Returns the Jacobian of acceleration:
            Γ_ij = ∂g_i / ∂x_j

        This matches EXACTLY your provided implementation, including gradLog sign handling.
        """
        P_in = np.asarray(points)
        P = np.atleast_2d(np.asarray(points, dtype=np.float64))
        B = P.shape[0]
        eps = self.eps

        Omega, gradOmega = self._solid_angle_and_grad(P, self.v0, self.v1, self.v2, eps)

        # Edge endpoint vectors from field point P
        ra_vec, rb_vec, ra, rb = self._edge_vectors_and_lengths(P)

        s = ra + rb
        L = self._L_row  # (1,3) same as self.L[None,:]

        denom2 = (s * s - L * L)  # (B,3)

        # Validity mask (avoid divisions / invalid regions)
        ok = (L > eps) & (ra > eps) & (rb > eps) & (np.abs(denom2) > eps)

        # factor = 2L/(s^2 - L^2)
        with np.errstate(divide="ignore", invalid="ignore"):
            factor = (2.0 * L) / denom2  # (B,3)
        factor = np.where(ok, factor, 0.0)

        # Unit-direction sums: (A-P)/|A-P| + (B-P)/|B-P|
        inv_ra = np.zeros_like(ra)
        inv_rb = np.zeros_like(rb)
        inv_ra[ra > eps] = 1.0 / ra[ra > eps]
        inv_rb[rb > eps] = 1.0 / rb[rb > eps]
        dirsum = (ra_vec * inv_ra[:, :, None] + rb_vec * inv_rb[:, :, None])  # (B,3,3)

        # IMPORTANT SIGN HANDLING: DO NOT CHANGE 
        gradLog = np.zeros((B, 3, 3), dtype=np.float64)
        gradLog[ok] = (factor[ok])[:, None] * dirsum[ok]

        # Σ_e u_e ⊗ ∇logE_e
        edge_tensor_sum = np.einsum("ei,bej->bij", self.u_hat, gradLog, optimize=True)

        # n ⊗ ∇Omega
        face_tensor_sum = np.einsum("i,bj->bij", self.n_hat, gradOmega, optimize=True)

        Gamma = self.G * self.sigma * (edge_tensor_sum - face_tensor_sum)

        bad = ~np.isfinite(Gamma)
        if np.any(bad):
            Gamma[bad] = 0.0

        return Gamma[0] if P_in.ndim == 1 else Gamma

    # -----------------------------
    # PARALLEL WRAPPERS
    # -----------------------------
    def _state_dict(self) -> dict:
        verts = np.ascontiguousarray(np.stack([self.v0, self.v1, self.v2], axis=0))
        return {"vertices": verts, "G": self.G, "sigma": self.sigma, "eps": self.eps}

    def potential_parallel(self, points: np.ndarray, n_workers=None, chunk_size: int = 200_000) -> np.ndarray:
        P_in = np.asarray(points)
        if P_in.ndim == 1:
            return self.potential(P_in)

        P = np.atleast_2d(np.asarray(points, dtype=np.float64))
        n = P.shape[0]
        if n == 0:
            return self.potential(P)

        if n_workers is None:
            n_workers = max(1, (os.cpu_count() or 1) - 1)

        out = np.empty((n,), dtype=np.float64)
        state = self._state_dict()

        with ProcessPoolExecutor(max_workers=n_workers, initializer=_tri_worker_init, initargs=(state,)) as ex:
            futures = []
            for i, j, Pchunk in _chunk_points(P, chunk_size):
                futures.append((i, j, ex.submit(_tri_worker_potential, Pchunk)))
            for i, j, fut in futures:
                out[i:j] = fut.result()

        return out

    def acceleration_parallel(self, points: np.ndarray, n_workers=None, chunk_size: int = 120_000) -> np.ndarray:
        P_in = np.asarray(points)
        if P_in.ndim == 1:
            return self.acceleration(P_in)

        P = np.atleast_2d(np.asarray(points, dtype=np.float64))
        n = P.shape[0]
        if n == 0:
            return self.acceleration(P)

        if n_workers is None:
            n_workers = max(1, (os.cpu_count() or 1) - 1)

        out = np.empty((n, 3), dtype=np.float64)
        state = self._state_dict()

        with ProcessPoolExecutor(max_workers=n_workers, initializer=_tri_worker_init, initargs=(state,)) as ex:
            futures = []
            for i, j, Pchunk in _chunk_points(P, chunk_size):
                futures.append((i, j, ex.submit(_tri_worker_acceleration, Pchunk)))
            for i, j, fut in futures:
                out[i:j, :] = fut.result()

        return out

    def gravity_tensor_parallel(self, points: np.ndarray, n_workers=None, chunk_size: int = 60_000) -> np.ndarray:
        P_in = np.asarray(points)
        if P_in.ndim == 1:
            return self.gravity_tensor(P_in)

        P = np.atleast_2d(np.asarray(points, dtype=np.float64))
        n = P.shape[0]
        if n == 0:
            return self.gravity_tensor(P)

        if n_workers is None:
            n_workers = max(1, (os.cpu_count() or 1) - 1)

        out = np.empty((n, 3, 3), dtype=np.float64)
        state = self._state_dict()

        with ProcessPoolExecutor(max_workers=n_workers, initializer=_tri_worker_init, initargs=(state,)) as ex:
            futures = []
            for i, j, Pchunk in _chunk_points(P, chunk_size):
                futures.append((i, j, ex.submit(_tri_worker_tensor, Pchunk)))
            for i, j, fut in futures:
                out[i:j, :, :] = fut.result()

        return out
