% ======================================================================
% triangle_gravity_matlab.m
%
% Analytical gravitational field of a homogeneous triangle
% using closed-form expressions.
%
% This file implements the gravitational potential, acceleration, and
% gravitation-gradient tensor generated by a planar triangle with uniform
% surface density.
%
% The formulation is mathematically equivalent to the reference Python
% and Julia implementations and follows identical conventions for:
%   • Edge-based logarithmic terms
%   • Solid angle representation
%   • Safe-math regularization of singular configurations
%   • Deterministic handling of edges and vertices
%
% ----------------------------------------------------------------------
% DISPATCHER INTERFACE
%
%   tri = triangle_gravity_matlab('init', vertices, G, sigma, eps)
%
%   V   = triangle_gravity_matlab('potential_batch', ...
%           tri, points, parallel_threshold, chunk_size)
%
%   [gx,gy,gz] = triangle_gravity_matlab('acceleration_batch', ...
%           tri, points, parallel_threshold, chunk_size)
%
%   [G11,G12,G13,G21,G22,G23,G31,G32,G33] = ...
%           triangle_gravity_matlab('tensor_batch', ...
%           tri, points, parallel_threshold, chunk_size)
%
% ----------------------------------------------------------------------
% INPUT FORMAT
%
%   vertices : 3×3 double
%              rows are triangle vertices [v0; v1; v2]
%
%   points   : N×3 double
%              rows are observation points (x, y, z)
%
%   G        : gravitational constant
%   sigma    : surface density of the triangle
%   eps      : small regularization parameter for numerical safety
%
% ----------------------------------------------------------------------
% OUTPUT FORMAT
%
%   Potential      : N×1 vector
%   Acceleration   : gx, gy, gz (each N×1)
%   Gravity tensor : 9 component vectors (N×1 each), returned as
%                    G11 G12 G13
%                    G21 G22 G23
%                    G31 G32 G33
%
% The tensor is NOT symmetrized internally; symmetry can be imposed
% externally if desired.
%
% ----------------------------------------------------------------------
% IMPLEMENTATION NOTES
%
% • Uses solid-angle representation and its spatial gradient
% • Edge integrals follow the exact logarithmic formulation
% • Parallel execution supported via parfor for large N
% • Results agree to machine precision with Python and Julia versions
%
% ----------------------------------------------------------------------
% Author:
%   Thunendran Periyandy
%
% Purpose:
%   Cross-language validation and high-precision evaluation of analytical
%   gravitational fields for Polygon.
%
% ======================================================================

function varargout = triangle_gravity_matlab(action, varargin)
% triangle_gravity_matlab.m
%
% Dispatcher:
%   tri = triangle_gravity_matlab('init', vertices, G, sigma, eps)
%   V   = triangle_gravity_matlab('potential_batch', tri, points, parallel_threshold, chunk_size)
%   [gx,gy,gz] = triangle_gravity_matlab('acceleration_batch', tri, points, parallel_threshold, chunk_size)
%   [G11,G12,G13,G21,G22,G23,G31,G32,G33] = triangle_gravity_matlab('tensor_batch', tri, points, parallel_threshold, chunk_size)

    switch lower(action)
        case 'init'
            varargout{1} = tri_init(varargin{:});

        case 'potential_batch'
            varargout{1} = potential_batch_triangle(varargin{:});

        case 'acceleration_batch'
            [varargout{1}, varargout{2}, varargout{3}] = acceleration_batch_triangle(varargin{:});

        case 'tensor_batch'
            [varargout{1}, varargout{2}, varargout{3}, varargout{4}, varargout{5}, ...
             varargout{6}, varargout{7}, varargout{8}, varargout{9}] = tensor_batch_triangle(varargin{:});

        otherwise
            error('Unknown action "%s".', action);
    end
end

% ======================================================================
% INIT
% ======================================================================
function tri = tri_init(vertices, G, sigma, eps)
    if nargin < 2 || isempty(G);     G = 1.0; end
    if nargin < 3 || isempty(sigma); sigma = 1.0; end
    if nargin < 4 || isempty(eps);   eps = 0.0; end

    v = double(vertices);
    assert(isequal(size(v), [3,3]), 'vertices must be 3x3: rows [v0; v1; v2].');

    v0 = v(1,:); v1 = v(2,:); v2 = v(3,:);

    n_raw  = cross(v1 - v0, v2 - v0);
    n_norm = norm(n_raw);
    assert(isfinite(n_norm) && n_norm > eps, 'Degenerate triangle (area~0) or invalid normal.');
    n_hat = n_raw / n_norm;

    ea = [v0; v1; v2];     % 3x3
    eb = [v1; v2; v0];     % 3x3
    evec = eb - ea;        % 3x3
    Lcol = sqrt(sum(evec.^2, 2)); % 3x1
    assert(all(isfinite(Lcol)) && all(Lcol > eps), 'Degenerate edge length encountered.');

    t_hat = evec ./ Lcol;                           % 3x3
    u_hat = cross(t_hat, repmat(n_hat,3,1), 2);     % 3x3

    tri.G     = double(G);
    tri.sigma = double(sigma);
    tri.eps   = double(eps);

    tri.v0 = v0; tri.v1 = v1; tri.v2 = v2;
    tri.n_hat = n_hat;

    tri.ea = ea; tri.eb = eb;
    tri.L  = Lcol(:).';      % 1x3 row
    tri.u_hat = u_hat;       % 3x3 (edge rows)
end

% ======================================================================
% Special MATH
% ======================================================================
function out = sp_log_vec(x)
    x = double(x);
    out = zeros(size(x));
    ok = (x > 0.0);
    out(ok) = log(x(ok));
    out(~isfinite(out)) = 0.0;
end

function out = atan2_like_vec(y, x, epsv)
    if nargin < 3 || isempty(epsv); epsv = 0.0; end
    y = double(y); x = double(x);
    out = zeros(size(y));

    x_ok = abs(x) > epsv;
    base = zeros(size(out));
    base(x_ok) = atan(y(x_ok) ./ x(x_ok));

    corr = zeros(size(out));
    negx = x_ok & (x < 0.0);
    corr(negx & (y >= 0.0)) = pi;
    corr(negx & (y <  0.0)) = -pi;

    out(x_ok) = base(x_ok) + corr(x_ok);

    x_bad = ~x_ok;
    out(x_bad & (y >  epsv)) =  0.5*pi;
    out(x_bad & (y < -epsv)) = -0.5*pi;

    out(~isfinite(out)) = 0.0;
end

% ======================================================================
% LOG TERM
% ======================================================================
function logE = log_term(ra, rb, Lrow, epsv)
    ra = double(ra); rb = double(rb);
    L  = double(Lrow); if iscolumn(L); L = L.'; end % 1x3

    s   = ra + rb;     % Bx3
    den = s - L;       % Bx3 (implicit expansion)

    ok  = (L > epsv) & (den > epsv);
    ratio = (s + L) ./ den;

    ok2 = ok & (ratio > 0.0);
    logE = zeros(size(s));
    logE(ok2) = sp_log_vec(ratio(ok2));
    logE(~isfinite(logE)) = 0.0;
end

% ======================================================================
% SOLID ANGLE + GRAD
% ======================================================================
function [Omega, gradOmega] = solid_angle_and_grad(P, v0, v1, v2, epsv)
    P = double(P);
    B = size(P,1);

    r0 = repmat(v0,B,1) - P;
    r1 = repmat(v1,B,1) - P;
    r2 = repmat(v2,B,1) - P;

    r0n = sqrt(sum(r0.^2,2));
    r1n = sqrt(sum(r1.^2,2));
    r2n = sqrt(sum(r2.^2,2));

    c12 = cross(r1, r2, 2);
    c20 = cross(r2, r0, 2);
    c01 = cross(r0, r1, 2);

    T = sum(c12 .* r0, 2);

    d01 = sum(r0 .* r1, 2);
    d12 = sum(r1 .* r2, 2);
    d20 = sum(r2 .* r0, 2);

    D = (r0n .* r1n .* r2n + d01 .* r2n + d12 .* r0n + d20 .* r1n);

    Omega = 2.0 * atan2_like_vec(T, D, epsv);

    gradT = -(c12 + c20 + c01);   % Bx3

    inv_r0 = zeros(B,1); inv_r1 = zeros(B,1); inv_r2 = zeros(B,1);
    ok0 = r0n > epsv; ok1 = r1n > epsv; ok2 = r2n > epsv;
    inv_r0(ok0) = 1.0 ./ r0n(ok0);
    inv_r1(ok1) = 1.0 ./ r1n(ok1);
    inv_r2(ok2) = 1.0 ./ r2n(ok2);

    grad_r0n = -r0 .* repmat(inv_r0,1,3);
    grad_r1n = -r1 .* repmat(inv_r1,1,3);
    grad_r2n = -r2 .* repmat(inv_r2,1,3);

    grad_d01 = -(r0 + r1);
    grad_d12 = -(r1 + r2);
    grad_d20 = -(r2 + r0);

    t01 = repmat(r1n.*r2n,1,3);
    t02 = repmat(r0n.*r2n,1,3);
    t03 = repmat(r0n.*r1n,1,3);

    gradD1 = grad_r0n .* t01 + grad_r1n .* t02 + grad_r2n .* t03;
    gradD2 = grad_d01 .* repmat(r2n,1,3) + grad_r2n .* repmat(d01,1,3);
    gradD3 = grad_d12 .* repmat(r0n,1,3) + grad_r0n .* repmat(d12,1,3);
    gradD4 = grad_d20 .* repmat(r1n,1,3) + grad_r1n .* repmat(d20,1,3);

    gradD = gradD1 + gradD2 + gradD3 + gradD4;

    denom = T.*T + D.*D;
    gradOmega = zeros(B,3);

    ok = denom > epsv;
    denom_ok = denom(ok);
    gradOmega(ok,:) = 2.0 * ( (repmat(D(ok),1,3).*gradT(ok,:) - repmat(T(ok),1,3).*gradD(ok,:)) ./ repmat(denom_ok,1,3) );

    Omega(~isfinite(Omega)) = 0.0;
    gradOmega(~isfinite(gradOmega)) = 0.0;
end

% ======================================================================
% POTENTIAL CORE
% ======================================================================
function V = triangle_potential_vectorized(tri, points)
    P = double(points);
    B = size(P,1);
    epsv = tri.eps;

    z = sum((repmat(tri.v0,B,1) - P) .* repmat(tri.n_hat,B,1), 2);
    [Omega, ~] = solid_angle_and_grad(P, tri.v0, tri.v1, tri.v2, epsv);

    ea = tri.ea; eb = tri.eb;

    ra_vec = zeros(B,3,3);
    rb_vec = zeros(B,3,3);
    for e = 1:3
        ra_vec(:,e,1) = ea(e,1) - P(:,1);
        ra_vec(:,e,2) = ea(e,2) - P(:,2);
        ra_vec(:,e,3) = ea(e,3) - P(:,3);

        rb_vec(:,e,1) = eb(e,1) - P(:,1);
        rb_vec(:,e,2) = eb(e,2) - P(:,2);
        rb_vec(:,e,3) = eb(e,3) - P(:,3);
    end

    ra = sqrt(sum(ra_vec.^2, 3)); % Bx3
    rb = sqrt(sum(rb_vec.^2, 3)); % Bx3

    p = zeros(B,3);
    for e = 1:3
        uh = tri.u_hat(e,:); % 1x3
        p(:,e) = ra_vec(:,e,1)*uh(1) + ra_vec(:,e,2)*uh(2) + ra_vec(:,e,3)*uh(3);
    end

    logE = log_term(ra, rb, tri.L, epsv);
    edge_sum = sum(p .* logE, 2);

    V = tri.G * tri.sigma * (edge_sum - z .* Omega);
    V(~isfinite(V)) = 0.0;
end

function V = potential_batch_triangle(tri, points, parallel_threshold, chunk_size)
    if nargin < 3 || isempty(parallel_threshold); parallel_threshold = 50000; end
    if nargin < 4 || isempty(chunk_size);         chunk_size = 10000; end

    pts = double(points);
    N = size(pts,1);

    if N < parallel_threshold
        V = triangle_potential_vectorized(tri, pts);
        return
    end

    nChunks = ceil(N / chunk_size);
    outCell = cell(nChunks,1);

    parfor c = 1:nChunks
        i1 = (c-1)*chunk_size + 1;
        i2 = min(c*chunk_size, N);
        outCell{c} = triangle_potential_vectorized(tri, pts(i1:i2,:));
    end

    V = vertcat(outCell{:});
end

% ======================================================================
% ACCELERATION CORE
% ======================================================================
function [gx,gy,gz] = triangle_acceleration_vectorized(tri, points)
    P = double(points);
    B = size(P,1);
    epsv = tri.eps;

    [Omega, ~] = solid_angle_and_grad(P, tri.v0, tri.v1, tri.v2, epsv);

    ea = tri.ea; eb = tri.eb;

    ra = zeros(B,3);
    rb = zeros(B,3);
    for e = 1:3
        rax = ea(e,1) - P(:,1); ray = ea(e,2) - P(:,2); raz = ea(e,3) - P(:,3);
        rbx = eb(e,1) - P(:,1); rby = eb(e,2) - P(:,2); rbz = eb(e,3) - P(:,3);
        ra(:,e) = sqrt(rax.*rax + ray.*ray + raz.*raz);
        rb(:,e) = sqrt(rbx.*rbx + rby.*rby + rbz.*rbz);
    end

    logE = log_term(ra, rb, tri.L, epsv); % Bx3

    ux = tri.u_hat(:,1).'; uy = tri.u_hat(:,2).'; uz = tri.u_hat(:,3).'; % 1x3
    ex = sum(logE .* repmat(ux,B,1), 2);
    ey = sum(logE .* repmat(uy,B,1), 2);
    ez = sum(logE .* repmat(uz,B,1), 2);

    fx = -Omega .* tri.n_hat(1);
    fy = -Omega .* tri.n_hat(2);
    fz = -Omega .* tri.n_hat(3);

    gx = tri.G * tri.sigma * (ex + fx);
    gy = tri.G * tri.sigma * (ey + fy);
    gz = tri.G * tri.sigma * (ez + fz);

    gx(~isfinite(gx)) = 0.0;
    gy(~isfinite(gy)) = 0.0;
    gz(~isfinite(gz)) = 0.0;
end

function [gx,gy,gz] = acceleration_batch_triangle(tri, points, parallel_threshold, chunk_size)
    if nargin < 3 || isempty(parallel_threshold); parallel_threshold = 50000; end
    if nargin < 4 || isempty(chunk_size);         chunk_size = 10000; end

    pts = double(points);
    N = size(pts,1);

    if N < parallel_threshold
        [gx,gy,gz] = triangle_acceleration_vectorized(tri, pts);
        return
    end

    nChunks = ceil(N / chunk_size);
    outCell = cell(nChunks,1);

    parfor c = 1:nChunks
        i1 = (c-1)*chunk_size + 1;
        i2 = min(c*chunk_size, N);
        [cgx,cgy,cgz] = triangle_acceleration_vectorized(tri, pts(i1:i2,:));
        outCell{c} = [cgx,cgy,cgz];
    end

    out = vertcat(outCell{:});
    gx = out(:,1); gy = out(:,2); gz = out(:,3);
end

% ======================================================================
% TENSOR CORE
% ======================================================================
function [G11,G12,G13,G21,G22,G23,G31,G32,G33] = triangle_tensor_vectorized(tri, points)
    P = double(points);
    B = size(P,1);
    epsv = tri.eps;

    [~, gradOmega] = solid_angle_and_grad(P, tri.v0, tri.v1, tri.v2, epsv);

    ea = tri.ea; eb = tri.eb;

    ra_vec = zeros(B,3,3);
    rb_vec = zeros(B,3,3);
    ra = zeros(B,3);
    rb = zeros(B,3);

    for e = 1:3
        rax = ea(e,1) - P(:,1); ray = ea(e,2) - P(:,2); raz = ea(e,3) - P(:,3);
        rbx = eb(e,1) - P(:,1); rby = eb(e,2) - P(:,2); rbz = eb(e,3) - P(:,3);

        ra_vec(:,e,1) = rax; ra_vec(:,e,2) = ray; ra_vec(:,e,3) = raz;
        rb_vec(:,e,1) = rbx; rb_vec(:,e,2) = rby; rb_vec(:,e,3) = rbz;

        ra(:,e) = sqrt(rax.*rax + ray.*ray + raz.*raz);
        rb(:,e) = sqrt(rbx.*rbx + rby.*rby + rbz.*rbz);
    end

    s = ra + rb;                 % Bx3
    L = repmat(tri.L, B, 1);     % Bx3
    denom2 = s.*s - L.*L;

    ok = (L > epsv) & (ra > epsv) & (rb > epsv) & (abs(denom2) > epsv);

    factor = zeros(B,3);
    factor(ok) = (2.0 .* L(ok)) ./ denom2(ok);

    inv_ra = zeros(B,3); inv_rb = zeros(B,3);
    inv_ra(ra > epsv) = 1.0 ./ ra(ra > epsv);
    inv_rb(rb > epsv) = 1.0 ./ rb(rb > epsv);

    dirsum = ra_vec .* inv_ra(:,:,ones(1,3)) + rb_vec .* inv_rb(:,:,ones(1,3));

    gradLog = zeros(B,3,3);
    for e = 1:3
        fe = factor(:,e);
        gradLog(:,e,1) = fe .* dirsum(:,e,1);
        gradLog(:,e,2) = fe .* dirsum(:,e,2);
        gradLog(:,e,3) = fe .* dirsum(:,e,3);

        m = ~ok(:,e);
        gradLog(m,e,1) = 0.0; gradLog(m,e,2) = 0.0; gradLog(m,e,3) = 0.0;
    end

    u = tri.u_hat; % 3x3 (edges in rows)
    ex11 = u(1,1)*gradLog(:,1,1) + u(2,1)*gradLog(:,2,1) + u(3,1)*gradLog(:,3,1);
    ex12 = u(1,1)*gradLog(:,1,2) + u(2,1)*gradLog(:,2,2) + u(3,1)*gradLog(:,3,2);
    ex13 = u(1,1)*gradLog(:,1,3) + u(2,1)*gradLog(:,2,3) + u(3,1)*gradLog(:,3,3);

    ex21 = u(1,2)*gradLog(:,1,1) + u(2,2)*gradLog(:,2,1) + u(3,2)*gradLog(:,3,1);
    ex22 = u(1,2)*gradLog(:,1,2) + u(2,2)*gradLog(:,2,2) + u(3,2)*gradLog(:,3,2);
    ex23 = u(1,2)*gradLog(:,1,3) + u(2,2)*gradLog(:,2,3) + u(3,2)*gradLog(:,3,3);

    ex31 = u(1,3)*gradLog(:,1,1) + u(2,3)*gradLog(:,2,1) + u(3,3)*gradLog(:,3,1);
    ex32 = u(1,3)*gradLog(:,1,2) + u(2,3)*gradLog(:,2,2) + u(3,3)*gradLog(:,3,2);
    ex33 = u(1,3)*gradLog(:,1,3) + u(2,3)*gradLog(:,2,3) + u(3,3)*gradLog(:,3,3);

    nx = tri.n_hat(1); ny = tri.n_hat(2); nz = tri.n_hat(3);
    gOx = gradOmega(:,1); gOy = gradOmega(:,2); gOz = gradOmega(:,3);

    fx11 = nx*gOx; fx12 = nx*gOy; fx13 = nx*gOz;
    fx21 = ny*gOx; fx22 = ny*gOy; fx23 = ny*gOz;
    fx31 = nz*gOx; fx32 = nz*gOy; fx33 = nz*gOz;

    sconst = tri.G * tri.sigma;

    G11 = sconst * (ex11 - fx11);
    G12 = sconst * (ex12 - fx12);
    G13 = sconst * (ex13 - fx13);

    G21 = sconst * (ex21 - fx21);
    G22 = sconst * (ex22 - fx22);
    G23 = sconst * (ex23 - fx23);

    G31 = sconst * (ex31 - fx31);
    G32 = sconst * (ex32 - fx32);
    G33 = sconst * (ex33 - fx33);

    G11(~isfinite(G11)) = 0.0; G12(~isfinite(G12)) = 0.0; G13(~isfinite(G13)) = 0.0;
    G21(~isfinite(G21)) = 0.0; G22(~isfinite(G22)) = 0.0; G23(~isfinite(G23)) = 0.0;
    G31(~isfinite(G31)) = 0.0; G32(~isfinite(G32)) = 0.0; G33(~isfinite(G33)) = 0.0;
end

function [G11,G12,G13,G21,G22,G23,G31,G32,G33] = tensor_batch_triangle(tri, points, parallel_threshold, chunk_size)
    if nargin < 3 || isempty(parallel_threshold); parallel_threshold = 50000; end
    if nargin < 4 || isempty(chunk_size);         chunk_size = 10000; end

    pts = double(points);
    N = size(pts,1);

    if N < parallel_threshold
        [G11,G12,G13,G21,G22,G23,G31,G32,G33] = triangle_tensor_vectorized(tri, pts);
        return
    end

    nChunks = ceil(N / chunk_size);
    outCell = cell(nChunks,1);

    parfor c = 1:nChunks
        i1 = (c-1)*chunk_size + 1;
        i2 = min(c*chunk_size, N);
        [c11,c12,c13,c21,c22,c23,c31,c32,c33] = triangle_tensor_vectorized(tri, pts(i1:i2,:));
        outCell{c} = [c11,c12,c13,c21,c22,c23,c31,c32,c33];
    end

    out = vertcat(outCell{:});
    G11 = out(:,1); G12 = out(:,2); G13 = out(:,3);
    G21 = out(:,4); G22 = out(:,5); G23 = out(:,6);
    G31 = out(:,7); G32 = out(:,8); G33 = out(:,9);
end
