"""
Analytical Gravitational Potential of Planar Polygonal Mass Elements
===================================================================

This module provides an exact analytical formulation for the gravitational
potential generated by a homogeneous planar rectangle, evaluated at
arbitrary field points in three-dimensional space.

The implementation follows closed-form expressions derived from Newtonian
gravitational theory and is suitable for use as a fundamental surface-mass
primitive in polygonal and polyhedral gravity modeling.

Input
-----
Field points are specified by Cartesian coordinates (x, y, z).
The rectangular lamina is defined by half-dimensions L and B, surface
mass density sigma, and gravitational constant G.

Output
------
The gravitational potential values U are returned, corresponding to the
Newtonian gravitational potential evaluated at the specified field points.

Batch evaluation
----------------
For efficient evaluation at a large number of field points, the function
``potential_batch_rectangle`` accepts an array of points with shape (N, 3)
and returns an array of potential values. For sufficiently large N, the
computation is automatically vectorized and parallelized across available
CPU cores.

Author
------
Thunendran Periyandy
Division of Geodetic Science
The Ohio State University

"""


import numpy as np
from multiprocessing import Pool, cpu_count

from RectangleGravitationalField.safe_math import sp_log, sp_arctan


# =========================================================
# VECTORIZED SAFE WRAPPERS
# =========================================================

# Probe scalar behavior once 
_SPLOG_AT_ZERO = float(sp_log(0.0))
_SPLOG_AT_NEG  = float(sp_log(-1.0))

# arctan: probe the 0/0 convention 
_SPARCTAN_00 = float(sp_arctan(0.0, 0.0))

def _sp_log_vec(x):
    """
    Vector-safe log that matches scalar sp_log logic exactly.
    """
    x = np.asarray(x, dtype=float)

    out = np.empty_like(x, dtype=float)

    pos = x > 0.0
    zero = x == 0.0
    neg = ~pos & ~zero

    out[pos] = np.log(x[pos])
    out[zero] = _SPLOG_AT_ZERO
    out[neg] = _SPLOG_AT_NEG

    return out

def _sp_arctan_vec(y, x):
    """
    Vector-safe arctan that matches scalar sp_arctan on the (0,0) case.
    Else use np.arctan2 (vectorized, stable).
    """
    y = np.asarray(y, dtype=float)
    x = np.asarray(x, dtype=float)

    out = np.arctan2(y, x)

    both0 = (y == 0.0) & (x == 0.0)
    if np.any(both0):
        out = out.copy()
        out[both0] = _SPARCTAN_00

    return out


# =========================================================
# SCALAR VERSION 
# =========================================================

def gravitational_potential_rectangle(x, y, z, L, B, sigma, G=1.0, eps=1e-15):
    u1 = (L - x)
    u2 = -(L + x)
    v1 = (B - y)
    v2 = -(B + y)

    zz = z if abs(z) > eps else (eps if z >= 0 else -eps)

    Vsum = 0.0
    for (ui, vj, s) in (
        (u1, v1, +1.0),
        (u1, v2, -1.0),
        (u2, v1, -1.0),
        (u2, v2, +1.0),
    ):
        r = np.sqrt(ui*ui + vj*vj + zz*zz)
        Vsum += s * (
            ui * sp_log(vj + r)
            + vj * sp_log(ui + r)
            - zz * sp_arctan(ui * vj, zz * r)
        )

    return G * sigma * Vsum


# =========================================================
# VECTORIZED POTENTIAL
# =========================================================

def _rectangle_potential_vectorized(x, y, z, L, B, sigma, G=1.0, eps=1e-15):
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    z = np.asarray(z, dtype=float)

    # signed z (only affects exact plane handling)
    zz = np.where(np.abs(z) > eps, z, np.where(z >= 0.0, eps, -eps))
    zz4 = zz[:, None]

    # corners (N,4) in scalar loop order
    u = np.stack([L - x, L - x, -(L + x), -(L + x)], axis=1)
    v = np.stack([B - y, -(B + y), B - y, -(B + y)], axis=1)
    s = np.array([+1.0, -1.0, -1.0, +1.0])

    r = np.sqrt(u*u + v*v + zz4*zz4)

    # log terms: must preserve your scalar safe_math behavior
    term_log = (
        u * _sp_log_vec(v + r) +
        v * _sp_log_vec(u + r)
    )

    # arctan term: preserve scalar sp_arctan behavior exactly 
    # Evaluate sp_arctan elementwise but only 4 corners
    num = u * v
    den = zz4 * r

    atan = np.empty_like(num, dtype=float)
    for k in range(4):
        # apply scalar sp_arctan on arrays safely via np.frompyfunc (fast enough for 4*N)
        f = np.frompyfunc(lambda a, b: sp_arctan(float(a), float(b)), 2, 1)
        atan[:, k] = f(num[:, k], den[:, k]).astype(float)

    term = term_log - zz4 * atan

    V = np.sum(s * term, axis=1)
    return G * sigma * V



def _rect_chunk(args):
    x, y, z, L, B, sigma, G, eps = args
    return _rectangle_potential_vectorized(x, y, z, L, B, sigma, G, eps)


def potential_batch_rectangle(points, L, B, sigma, G=1.0, eps=1e-15,
                              parallel_threshold=50_000, chunk_size=10_000):
    pts = np.asarray(points, dtype=float)
    if pts.ndim != 2 or pts.shape[1] != 3:
        raise ValueError("points must have shape (N,3)")

    x, y, z = pts[:, 0], pts[:, 1], pts[:, 2]
    N = x.size

    if N < parallel_threshold:
        return _rectangle_potential_vectorized(x, y, z, L, B, sigma, G, eps)

    print(f"Rectangle potential: vectorized + parallel ({cpu_count()} CPUs)")

    chunks = []
    for i in range(0, N, chunk_size):
        sl = slice(i, i + chunk_size)
        chunks.append((x[sl], y[sl], z[sl], L, B, sigma, G, eps))

    with Pool(cpu_count()) as pool:
        out = pool.map(_rect_chunk, chunks)

    return np.concatenate(out)

