"""
Analytical Gravitational Tensor of Planar Polygonal Mass Elements
================================================================

This module provides an exact analytical formulation for the gravitational
(second-derivative) tensor generated by a homogeneous planar rectangle,
evaluated at arbitrary field points in three-dimensional space.

The implementation follows closed-form expressions derived from Newtonian
gravitational theory and represents the spatial second derivatives of the
analytical gravitational potential. The formulation is suitable for use as
a fundamental surface-mass primitive in polygonal and polyhedral gravity
modeling.

Input
-----
Field points are specified by Cartesian coordinates (x, y, z).
The rectangular lamina is defined by half-dimensions L and B, reference plane
location z_r, surface mass density rho_surf, and gravitational constant G_const.

Output
------
The gravitational tensor components are returned as
(Vxx, Vyy, Vzz, Vxy, Vxz, Vyz), corresponding to the second spatial derivatives
of the gravitational potential evaluated at the specified field points.

Batch evaluation
----------------
For efficient evaluation at a large number of field points, the function
``tensor_batch_rectangle`` accepts an array of points with shape (N, 3) and
returns arrays of tensor components (Vxx, Vyy, Vzz, Vxy, Vxz, Vyz). For
sufficiently large N, the computation is automatically vectorized and
parallelized across available CPU cores.

Author
------
Thunendran Periyandy
Division of Geodetic Science
The Ohio State University

"""



# RectangleGravitationalField/rectangle_tensor.py

import numpy as np
from multiprocessing import Pool, cpu_count

from .safe_math import sp_log, sp_arctan  


# =========================================================
# SCALAR CORNERS
# =========================================================
def _rectangle_corners(x, y, L, B):
    Xb = np.array([L - x, -(L + x)], dtype=float)
    Yb = np.array([B - y, -(B + y)], dtype=float)

    for ix in range(2):
        for iy in range(2):
            X = Xb[ix]
            Y = Yb[iy]
            sign = (-1) ** (ix + iy)
            yield X, Y, sign


# =========================================================
# SCALAR TENSOR FUNCTIONS
# =========================================================
def gravitational_Vxx_rectangle(x, y, z, L, B, z_r, G_const, rho_surf):
    Z = z - z_r
    S = 0.0
    with np.errstate(divide="ignore", invalid="ignore", over="ignore", under="ignore"):
        for X, Y, sgn in _rectangle_corners(x, y, L, B):
            r = np.sqrt(X*X + Y*Y + Z*Z)
            S += sgn * (X / (r * (Y + r)))
    return G_const * rho_surf * S


def gravitational_Vyy_rectangle(x, y, z, L, B, z_r, G_const, rho_surf):
    Z = z - z_r
    S = 0.0
    with np.errstate(divide="ignore", invalid="ignore", over="ignore", under="ignore"):
        for X, Y, sgn in _rectangle_corners(x, y, L, B):
            r = np.sqrt(X*X + Y*Y + Z*Z)
            S += sgn * (Y / (r * (X + r)))
    return G_const * rho_surf * S


def gravitational_Vzz_rectangle(x, y, z, L, B, z_r, G_const, rho_surf):
    Z = z - z_r
    S = 0.0

    with np.errstate(divide="ignore", invalid="ignore", over="ignore", under="ignore"):
        for X, Y, sgn in _rectangle_corners(x, y, L, B):

            if Z == 0.0:
                r0 = np.sqrt(X*X + Y*Y)
                S += sgn * (r0 / (X * Y))   # SIGN FIX
                continue

            r2 = X*X + Y*Y + Z*Z
            r = np.sqrt(r2)

            num = (X * Y) * (X*X + Y*Y + 2.0*Z*Z)   # SIGN FIX
            den = r * ((Z*Z) * r2 + (X*X) * (Y*Y))

            S += sgn * (num / den)

    return G_const * rho_surf * S


def gravitational_Vxy_rectangle(x, y, z, L, B, z_r, G_const, rho_surf):
    Z = z - z_r
    S = 0.0
    with np.errstate(divide="ignore", invalid="ignore", over="ignore", under="ignore"):
        for X, Y, sgn in _rectangle_corners(x, y, L, B):
            r = np.sqrt(X*X + Y*Y + Z*Z)
            S += sgn * (1.0 / r)
    return G_const * rho_surf * S


def gravitational_Vxz_rectangle(x, y, z, L, B, z_r, G_const, rho_surf):
    Zp = z - z_r
    S = 0.0
    with np.errstate(divide="ignore", invalid="ignore", over="ignore", under="ignore"):
        for X, Y, sgn in _rectangle_corners(x, y, L, B):
            r = np.sqrt(X*X + Y*Y + Zp*Zp)
            S += sgn * (Zp / (r * (Y + r)))
    return G_const * rho_surf * S


def gravitational_Vyz_rectangle(x, y, z, L, B, z_r, G_const, rho_surf):
    Zp = z - z_r
    S = 0.0
    with np.errstate(divide="ignore", invalid="ignore", over="ignore", under="ignore"):
        for X, Y, sgn in _rectangle_corners(x, y, L, B):
            r = np.sqrt(X*X + Y*Y + Zp*Zp)
            S += sgn * (Zp / (r * (X + r)))
    return G_const * rho_surf * S


# =========================================================
# VECTORIZED CORE
# =========================================================
def _rectangle_tensor_vectorized(x, y, z, L, B, z_r, G_const, rho_surf):
    """
    Vectorized tensor for arrays x,y,z (shape (N,)).

    Returns:
      Vxx,Vyy,Vzz,Vxy,Vxz,Vyz arrays (N,)
    """
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    z = np.asarray(z, dtype=float)

    if x.shape != y.shape or x.shape != z.shape:
        raise ValueError("x,y,z must have same shape")

    Z = z - z_r
    Z4 = Z[:, None]

    # SAME corner order as scalar loops:
    # (X1,Y1),(X1,Y2),(X2,Y1),(X2,Y2)
    X = np.stack([L - x, L - x, -(L + x), -(L + x)], axis=1)
    Y = np.stack([B - y, -(B + y), B - y, -(B + y)], axis=1)
    S = np.array([+1.0, -1.0, -1.0, +1.0], dtype=float)

    r2 = X*X + Y*Y + Z4*Z4
    r = np.sqrt(r2)

    with np.errstate(divide="ignore", invalid="ignore", over="ignore", under="ignore"):

        # Vxx, Vyy
        Vxx = np.sum(S * (X / (r * (Y + r))), axis=1)
        Vyy = np.sum(S * (Y / (r * (X + r))), axis=1)

        # Vxy
        Vxy = np.sum(S * (1.0 / r), axis=1)

        # Vxz, Vyz
        Vxz = np.sum(S * (Z4 / (r * (Y + r))), axis=1)
        Vyz = np.sum(S * (Z4 / (r * (X + r))), axis=1)

        # Vzz with
        Vzz = np.zeros_like(Vxx)

        off = (Z != 0.0)
        if np.any(off):
            Xo = X[off]
            Yo = Y[off]
            Zo = Z4[off]
            r2o = r2[off]
            ro = r[off]

            num = (Xo * Yo) * (Xo*Xo + Yo*Yo + 2.0*Zo*Zo)   # SIGN FIX
            den = ro * ((Zo*Zo) * r2o + (Xo*Xo) * (Yo*Yo))

            Vzz[off] = np.sum(S * (num / den), axis=1)

        on = ~off
        if np.any(on):
            X0 = X[on]
            Y0 = Y[on]
            r0 = np.sqrt(X0*X0 + Y0*Y0)
            Vzz[on] = np.sum(S * (r0 / (X0 * Y0)), axis=1)   # SIGN FIX

    scale = G_const * rho_surf
    return (scale*Vxx, scale*Vyy, scale*Vzz, scale*Vxy, scale*Vxz, scale*Vyz)


# =========================================================
# CHUNK WORKER FOR PARALLEL BATCH
# =========================================================
def _rect_tensor_chunk(args):
    x, y, z, L, B, z_r, G_const, rho_surf = args
    return _rectangle_tensor_vectorized(x, y, z, L, B, z_r, G_const, rho_surf)


# =========================================================
# BATCH + PARALLEL
# =========================================================
def tensor_batch_rectangle(points, L, B, z_r, G_const, rho_surf,
                           parallel_threshold=50_000, chunk_size=10_000):
    """
    Evaluate rectangle tensor for N points.

    Returns:
        Vxx,Vyy,Vzz,Vxy,Vxz,Vyz arrays (N,)
    """
    pts = np.asarray(points, dtype=float)
    if pts.ndim != 2 or pts.shape[1] != 3:
        raise ValueError("points must be shape (N,3)")

    x, y, z = pts[:, 0], pts[:, 1], pts[:, 2]
    N = x.size

    if N < parallel_threshold:
        return _rectangle_tensor_vectorized(x, y, z, L, B, z_r, G_const, rho_surf)

    print(f"Rectangle tensor: vectorized + parallel ({cpu_count()} CPUs)")

    chunks = []
    for i in range(0, N, chunk_size):
        sl = slice(i, i + chunk_size)
        chunks.append((x[sl], y[sl], z[sl], L, B, z_r, G_const, rho_surf))

    with Pool(cpu_count()) as pool:
        out = pool.map(_rect_tensor_chunk, chunks)

    Vxx = np.concatenate([o[0] for o in out])
    Vyy = np.concatenate([o[1] for o in out])
    Vzz = np.concatenate([o[2] for o in out])
    Vxy = np.concatenate([o[3] for o in out])
    Vxz = np.concatenate([o[4] for o in out])
    Vyz = np.concatenate([o[5] for o in out])

    return Vxx, Vyy, Vzz, Vxy, Vxz, Vyz