"""
Analytical Gravitational Acceleration of Planar Polygonal Mass Elements
======================================================================

This module provides an exact analytical formulation for the gravitational
acceleration (gravity vector) generated by a homogeneous planar rectangle,
evaluated at arbitrary field points in three-dimensional space.

The implementation follows closed-form expressions derived from Newtonian
gravitational theory and represents the spatial gradient of the corresponding
analytical gravitational potential. The formulation is suitable for use as
a fundamental surface-mass primitive in polygonal and polyhedral gravity
modeling.

Input
-----
Field points are specified by Cartesian coordinates (x, y, z).
The rectangular lamina is defined by half-dimensions L and B, surface
mass density sigma, and gravitational constant G.

Output
------
The gravitational acceleration vector components (gx, gy, gz) are returned,
corresponding to the negative spatial gradient of the gravitational potential
evaluated at the specified field points.

Batch evaluation
----------------
For efficient evaluation at a large number of field points, the function
``acceleration_batch_rectangle`` accepts an array of points with shape (N, 3)
and returns arrays of acceleration components (gx, gy, gz). For sufficiently
large N, the computation is automatically vectorized and parallelized across
available CPU cores.

Author
------
Thunendran Periyandy
Division of Geodetic Science
The Ohio State University

"""



import numpy as np
from multiprocessing import Pool, cpu_count

from RectangleGravitationalField.safe_math import sp_log, sp_arctan


# =========================================================
# VECTORIZED SAFE WRAPPERS 
# =========================================================

_SPLOG_AT_ZERO = float(sp_log(0.0))
_SPLOG_AT_NEG  = float(sp_log(-1.0))
_SPARCTAN_00   = float(sp_arctan(0.0, 0.0))

def _sp_log_vec(x):
    x = np.asarray(x, dtype=float)
    out = np.empty_like(x, dtype=float)

    pos = x > 0.0
    zero = x == 0.0
    neg = ~pos & ~zero

    out[pos] = np.log(x[pos])
    out[zero] = _SPLOG_AT_ZERO
    out[neg] = _SPLOG_AT_NEG
    return out

def _sp_arctan_vec(y, x):
    y = np.asarray(y, dtype=float)
    x = np.asarray(x, dtype=float)
    out = np.arctan2(y, x)
    both0 = (y == 0.0) & (x == 0.0)
    if np.any(both0):
        out = out.copy()
        out[both0] = _SPARCTAN_00
    return out


# =========================================================
# SCALAR FUNCTIONS
# =========================================================

def log_or_inf(A):
    if A == 0.0:
        return np.inf
    return sp_log(A)

def gravitational_gx_rectangle(x, y, z, L, B, sigma, G=1.0, eps=0.0):
    u = np.array([L - x, -(L + x)])
    v = np.array([B - y, -(B + y)])
    zz = z if abs(z) > eps else (eps if z >= 0 else -eps)

    ssum = 0.0
    for i in range(2):
        for j in range(2):
            ui = u[i]
            vj = v[j]
            rij = np.sqrt(ui*ui + vj*vj + zz*zz)
            s = (-1)**(i + j)

            A = vj + rij
            term = log_or_inf(A)

            if np.isinf(term):
                return -G * sigma * s * term

            ssum += s * term

    return -G * sigma * ssum


def gravitational_gy_rectangle(x, y, z, L, B, sigma, G=1.0, eps=0.0):
    u = np.array([L - x, -(L + x)])
    v = np.array([B - y, -(B + y)])
    zz = z if abs(z) > eps else (eps if z >= 0 else -eps)

    ssum = 0.0
    for i in range(2):
        for j in range(2):
            ui = u[i]
            vj = v[j]
            rij = np.sqrt(ui*ui + vj*vj + zz*zz)
            s = (-1)**(i + j)

            A = ui + rij
            term = log_or_inf(A)

            if np.isinf(term):
                return -G * sigma * s * term

            ssum += s * term

    return -G * sigma * ssum


def gravitational_gz_rectangle(x, y, z, L, B, sigma, G=1.0, eps=0.0):
    u = np.array([L - x, -(L + x)])
    v = np.array([B - y, -(B + y)])
    zz = z if abs(z) > eps else (eps if z >= 0 else -eps)

    ssum = 0.0
    for i in range(2):
        for j in range(2):
            ui = u[i]
            vj = v[j]
            rij = np.sqrt(ui*ui + vj*vj + zz*zz)
            s = (-1)**(i + j)
            ssum += s * sp_arctan(ui * vj, zz * rij)

    return -G * sigma * ssum


# =========================================================
# VECTORIZED CORE (FAST, PRESERVES log_or_inf RULE)
# =========================================================

def _rectangle_acceleration_vectorized(x, y, z, L, B, sigma, G=1.0, eps=0.0):
    """
    Vectorized rectangle acceleration for arrays x,y,z (shape (N,)).
    Preserves scalar gx/gy "log_or_inf" behavior (A==0 -> +inf with deterministic first-hit sign),
    and fixes gz by evaluating scalar sp_arctan elementwise (correct branch for negative z).

    Requires in module scope:
        - numpy as np
        - sp_arctan from RectangleGravitationalField.safe_math
        - _sp_log_vec (your vector-safe wrapper that matches scalar sp_log exactly)
    """
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    z = np.asarray(z, dtype=float)

    # signed epsilon handling (only affects points very near z=0)
    zz = np.where(np.abs(z) > eps, z, np.where(z >= 0.0, eps, -eps))
    zz4 = zz[:, None]

    # Corners in the SAME order as scalar loops:
    # (u1,v1), (u1,v2), (u2,v1), (u2,v2)
    u = np.stack([L - x, L - x, -(L + x), -(L + x)], axis=1)
    v = np.stack([B - y, -(B + y), B - y, -(B + y)], axis=1)
    s = np.array([+1.0, -1.0, -1.0, +1.0], dtype=float)

    r = np.sqrt(u*u + v*v + zz4*zz4)

    # ============================================================
    # gx: uses A = v + r, with log_or_inf(A)
    # ============================================================
    A_gx = v + r
    gx_term = _sp_log_vec(A_gx)                 # matches scalar sp_log behavior
    gx_term = np.where(A_gx == 0.0, np.inf, gx_term)  # log_or_inf(A)

    gx = -G * sigma * np.sum(s * gx_term, axis=1)

    # Scalar returns immediately if any A==0, with sign determined by FIRST hit
    hit = (A_gx == 0.0)
    if np.any(hit):
        has_hit = np.any(hit, axis=1)
        first_idx = np.argmax(hit, axis=1)      # returns 0 if no hit; masked by has_hit
        corner_sign = s[first_idx]
        gx = gx.copy()
        gx[has_hit] = -G * sigma * corner_sign[has_hit] * np.inf

    # ============================================================
    # gy: uses A = u + r, with log_or_inf(A)
    # ============================================================
    A_gy = u + r
    gy_term = _sp_log_vec(A_gy)
    gy_term = np.where(A_gy == 0.0, np.inf, gy_term)

    gy = -G * sigma * np.sum(s * gy_term, axis=1)

    hit = (A_gy == 0.0)
    if np.any(hit):
        has_hit = np.any(hit, axis=1)
        first_idx = np.argmax(hit, axis=1)
        corner_sign = s[first_idx]
        gy = gy.copy()
        gy[has_hit] = -G * sigma * corner_sign[has_hit] * np.inf

    # ============================================================
    # gz: MUST match scalar sp_arctan(ui*vj, zz*rij) branch exactly
    # ============================================================
    num = u * v
    den = zz4 * r

    # fast-enough: only 4*N scalar calls, preserves exact safe_math conventions
    f = np.frompyfunc(lambda a, b: sp_arctan(float(a), float(b)), 2, 1)

    gz_term = np.empty_like(num, dtype=float)
    # Corner loop (4 only) – vectorized over N points
    for k in range(4):
        gz_term[:, k] = f(num[:, k], den[:, k]).astype(float)

    gz = -G * sigma * np.sum(s * gz_term, axis=1)

    return gx, gy, gz



def _rect_acc_chunk(args):
    x, y, z, L, B, sigma, G, eps = args
    return _rectangle_acceleration_vectorized(x, y, z, L, B, sigma, G, eps)


def acceleration_batch_rectangle(points, L, B, sigma, G=1.0, eps=0.0,
                                 parallel_threshold=50_000, chunk_size=10_000):
    pts = np.asarray(points, dtype=float)
    if pts.ndim != 2 or pts.shape[1] != 3:
        raise ValueError("points must be shape (N,3)")

    x, y, z = pts[:, 0], pts[:, 1], pts[:, 2]
    N = x.size

    if N < parallel_threshold:
        return _rectangle_acceleration_vectorized(x, y, z, L, B, sigma, G, eps)

    print(f"Rectangle acceleration: vectorized + parallel ({cpu_count()} CPUs)")

    chunks = []
    for i in range(0, N, chunk_size):
        sl = slice(i, i + chunk_size)
        chunks.append((x[sl], y[sl], z[sl], L, B, sigma, G, eps))

    with Pool(cpu_count()) as pool:
        out = pool.map(_rect_acc_chunk, chunks)

    gx = np.concatenate([o[0] for o in out])
    gy = np.concatenate([o[1] for o in out])
    gz = np.concatenate([o[2] for o in out])

    return gx, gy, gz

